version: '3.8'

services:
  api:
    build: .
    container_name: storages-api
    ports:
      - "3003:3003"
    env_file:
      - .env
    volumes:
      # Format: /path/di/komputer/user:/path/di/dalam/docker
      - /run/media/roniserv/V-GEN:/run/media/roniserv/V-GEN
      - /home/roniserv/:/home/roniserv/
    restart: unless-stopped