version: '3.8'

services:
  api:
    build: .
    container_name: storages-api
    ports:
      - "3003:3003"
    env_file:
      - .env
    volumes:
      - ${HOST_PATH_SSD}:${HOST_PATH_SSD}
      - ${HOST_PATH_HDD}:${HOST_PATH_HDD}
    restart: unless-stopped